# Generated by Django 5.2.15 on 2026-06-10 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.URLField(blank=True, max_length=255, null=True, verbose_name='图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='状态 1启用 0禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.goodscategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_category',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='副标题')),
                ('main_image', models.URLField(blank=True, max_length=255, null=True, verbose_name='主图')),
                ('images', models.TextField(blank=True, null=True, verbose_name='详情图列表(JSON)')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='商品详情HTML')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低售价')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('stock', models.IntegerField(default=0, verbose_name='总库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('status', models.IntegerField(default=1, verbose_name='状态 1上架 0下架')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热卖')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.goodscategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.CharField(max_length=500, verbose_name='规格描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='SKU价格')),
                ('stock', models.IntegerField(default=0, verbose_name='SKU库存')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='SKU配图')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'goods_sku',
            },
        ),
    ]
