# Generated by Django 5.2.15 on 2026-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('image_url', models.URLField(max_length=255, verbose_name='图片URL')),
                ('link_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='跳转链接')),
                ('link_type', models.IntegerField(choices=[(1, '不跳转'), (2, '商品详情'), (3, '分类列表')], default=1, verbose_name='跳转类型')),
                ('link_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='跳转参数')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='1启用 0禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banner',
                'ordering': ['sort'],
            },
        ),
    ]
